version: "3.9"

services:
  java_app2:
    container_name: java_app2
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8082:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=Compra
    depends_on:
      - java_db
  java_db:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"